### ISSUE TITLE
Filebeats works with elasticsearch directly, but not through logstash

### ISSUE THREAD

**Issue by sunshineo** [spujadas/elk-docker#122]
Hi,

I downloaded filebeats directly from the source and following the tutorial.
It works at step 2 https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-configuration.html
But not at step 3 https://www.elastic.co/guide/en/beats/filebeat/current/config-filebeat-logstash.html

I tried a lot of things. I also copied the certificate files from this repo and put in the filebeat config file. But just does not work.

Anything helps. Thanks!
```
#----------------------------- Logstash output --------------------------------
output.logstash:
  # The Logstash hosts
  hosts: ["localhost:5044"]

  # Optional SSL. By default is off.
  # List of root certificates for HTTPS server verifications
  #ssl.certificate_authorities: ["/etc/pki/root/ca.pem"]

  # Certificate for SSL client authentication
  ssl.certificate: "/Users/ssun/Github/elk-docker/logstash-beats.crt"

  # Client Certificate Key
  ssl.key: "/Users/ssun/Github/elk-docker/logstash-beats.key"
```

**Comment by sunshineo** [comment]
so I put the crt file in the wrong place. The key file is not needed. This config works.
```
#----------------------------- Logstash output --------------------------------
output.logstash:
  # The Logstash hosts
  hosts: ["localhost:5044"]

  # Optional SSL. By default is off.
  # List of root certificates for HTTPS server verifications
  ssl.certificate_authorities: ["/Users/ssun/Github/elk-docker/logstash-beats.crt"]

  # Certificate for SSL client authentication
  #ssl.certificate: "/Users/ssun/Github/elk-docker/logstash-beats.crt"

  # Client Certificate Key
  #ssl.key: "/Users/ssun/Github/elk-docker/logstash-beats.key"
```
