### ISSUE TITLE
Logstash HTTP input doesn't work. Even after having changed docker-compose.yml.

### ISSUE THREAD

**Issue by carmelone** [spujadas/elk-docker#162]
I wanna use the https://www.elastic.co/blog/introducing-logstash-input-http-plugin but using **docker-compose.yml** as stated in your docs (http://elk-docker.readthedocs.io/):

```
elk:
  image: sebp/elk
  ports:
    - "5601:5601"
    - "9200:9200"
    - "5044:5044"
```

Using:

`$ curl -XPUT "http://localhost:5044/twitter/tweet/1" -d "test 1"`

I get

`curl: (52) Empty reply from server`

I already tried this in `docker-compose.yml`:

```
volumes:
      - ./config/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
```

like this:

```
input {
  http {
    host => '0.0.0.0'
    port => 5044
  }
}

output {
  elasticsearch {
    hosts => [ 'localhost' ]
  }
}
```
**How to?**

**Comment by spujadas** [comment]
For non-Docker-specific help with this image, e.g. for guidance on how to use Logstash plugins, please seek assistance from https://discuss.elastic.co/.

I do see two image-specific issues with your set-up however:

- In the image, port 5044 is used for Beats input (not HTTP input, which you're trying to send). You want to expose and publish an additional port, and configure Logstash's HTTP input plugin to use that port.

- Logstash's configuration file isn't located where your `volumes` directive is pointing (it is actually located in `/etc/logstash/conf.d`, see http://elk-docker.readthedocs.io/#updating-logstash-configuration).

**Comment by annevah** [comment]
@spujadas I am having trouble in sending logs from logstash http to elastic search.

Dockerfile:

```
FROM sebp/elk

WORKDIR ${LOGSTASH_HOME}
RUN gosu logstash bin/logstash-plugin install logstash-input-http
```

Docker compose looks like this:

```
elk:
    build:
      context: elk/
    container_name: elk
    volumes:
      - ./elk/logstash/pipeline:/etc/logstash/conf.d
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
      - "5000:5000"
```

/elk/logstash/pipeline

```
input {
	http {	
		port => "5000"
	}
}

output {
	elasticsearch {
		hosts => "elasticsearch:9200"
	}
}
```
Did try changing host to elk:9200, but did not work.

The build output:

```
4>Building elk
4>Step 1/3 : FROM sebp/elk
4> ---> cbc71866e440
4>Step 2/3 : WORKDIR ${LOGSTASH_HOME}
4> ---> Running in 78ca16be90c7
4>Removing intermediate container 78ca16be90c7
4> ---> 64bbda77a769
4>Step 3/3 : RUN gosu logstash bin/logstash-plugin install logstash-input-http
4> ---> Running in df994be34c69
4>Validating logstash-input-http
4>Installing logstash-input-http
4>Installation successful
4>Removing intermediate container df994be34c69
4> ---> 046b788573ba
4>Successfully built 046b788573ba
4>Successfully tagged dockercompose4330332928179791212_elk:latest
```

Am I missing something? localhost:5000 always returns Ok. But no logs are been listed in Kibana. If I directly write to elastic search then it is listed in Kibana.
