### ISSUE TITLE
Kibana service stops when basePath is set

### ISSUE THREAD

**Issue by rvolykh** [spujadas/elk-docker#176]
Image: sebp/elk:520 (same for 563)

I'm trying to starting container with 'docker-compose' when kibana.yml contains `basePath`. Logstash and elastic runs well, but kibana is stopped. `service kibana restart` inside container help it to start, but after a while shutdowns. Configs is available inside container. 
But when i start kibana from container manually as binary `./opt/kibana/bin/kibana` everything works like a charm. After that even after stopping kibana (manually started) and starting `service kibana start` (as a service) everything work fine even after container restarts. 
Probably, some problems with cache. Can you please, suggest where to dig in.

Thanks,

----------
docker-compose.ymp
```
elk:
        image: sebp/elk:520
        ports:
            - "9200:9200"   #elasticsearch
            - "5601:5601"   #kibana
            - "5044:5044"   #logstash
        volumes:
            - "./conf/kibana/kibana.yml:/opt/kibana/config/kibana.yml"  # old (4.x) location
            - "./conf/kibana/kibana.yml:/etc/kibana/config/kibana.yml"  # new (5.x) location
```
kibana.yml
```
server:
  basePath: "/kibana"
  host: "0.0.0.0"
```
Kibana logs:
```
{"type":"log","@timestamp":"2017-11-03T14:01:49Z","tags":["info","optimize"],"pid":190,"message":"Optimiz
ing and caching bundles for kibana, timelion and status_page. This may take a few minutes"}
```
