### ISSUE TITLE
Changing Logstash configuration

### ISSUE THREAD

**Issue by weeco** [spujadas/elk-docker#212]
I am struggling with my Elk stack + filebeat configuration and I am not sure why it's currently not working. After reading the docs I suspect that it's not working because I haven't configured Logstash to use the predefined beats-input.conf . Even though the doc mention that such a config file exists, it doesn't describe how to enable these config files?

My current docker-compose error logs look like this: https://hastebin.com/ekorodepus.php

## filebeat.yml file
```yml
filebeat.prospectors:
- type: docker
  paths:
   - "/var/lib/docker/containers/*/*.log"
  containers.ids: "*"

processors:
  - decode_json_fields:
      fields: ["message"]
      target: ""
      overwrite_keys: true
  - add_docker_metadata: ~

output.logstash:
  hosts: ["elk:5044"]
  certificate_authorities:
    - /etc/pki/tls/certs/logstash-beats.crt
  timeout: 45

logging.to_files: true
logging.to_syslog: false
```

Filebeat dockerfile:

```docker
FROM elastic/filebeat:6.3.1

COPY logstash-beats.key /etc/pki/tls/certs/logstash-beats.crt
COPY filebeat.yml /usr/share/filebeat/filebeat.yml

USER root
RUN chown root /etc/pki/tls/certs/logstash-beats.crt
RUN chown root /usr/share/filebeat/filebeat.yml
```
