### ISSUE TITLE
Kibana still using default port : 9200  after overwritten in  docker-compose.yml ?

### ISSUE THREAD

**Issue by jdang67** [spujadas/elk-docker#253]
Hi,
I am not sure this is the problem with this elk image or "Kibana". The following is my setup for my environment ( Window 10, docker-desktop: Version 2.0.0.3 (31259))
```
elk:
    image: sebp/elk
    container_name: elasticSearch-kibana-logstash
    ports:
      - "5602:5601"
      - "9202:9200"
      - "5046:5044"
```
The setup above works initially.  After playing with kibana for a while,  it stops working and here the logs:
```
elasticSearch-kibana-logstash | {"type":"log","@timestamp":"2019-02-17T15:42:02Z","tags":["warning","elasticsearch","admin"],"pid":281,"message":"Unable to revive connection:http://localhost:9200/"}
elasticSearch-kibana-logstash | {"type":"log","@timestamp":"2019-02-17T15:42:02Z","tags":["warning","elasticsearch","admin"],"pid":281,"message":"No living connections"}
```
Looks like this is Kibana's problem since I am not  able to use ElasticSearch/Kibana images directly because the same problem.

Thanks
