### ISSUE TITLE
Connecting custom container to elk

### ISSUE THREAD

**Issue by mimmozzo** [spujadas/elk-docker#27]
Hi,

first of all, thanks for your outstanding work. 
I am trying to connect my custom container to your ELK one to allow log collecting. In my custom container, all apps log to stdout, so I would like to simply pipe container logs into the ELK, without installing filebeat on the container itself.
I've tried with this docker-compose file:

```
version: '2'
services: 
    elk: 
        image: sebp/elk
        ports:
            - "5601:5601"
            - "9200:9200"
            - "5044:5044"
            - "5000:5000"
    tomcat-ad: 
        image: dr/my-tomcat
        ports: 
            - "8080:8080"
        links: 
            - elk
        logging: 
            driver: gelf
            options:  
                gelf-address: "udp://elk:5044"
                gelf-tag: "test-elk-tag"
```

but I get an error:
```
ps@ps-vm:~$ docker-compose up -d   
Creating ps_elk_1
Creating ps_tomcat-ad_1
ERROR: Failed to initialize logging driver: gelf: cannot connect to GELF endpoint: elk:5044 dial udp: lookup elk on 10.25.7.4:53: server misbehaving
```
Seems like the "elk" hostname is somehow not recognized, so the docker host tries to reach my network DNS server.
What do you think? Is this approach possible?
