### ISSUE TITLE
How to install logstash syslog input plugin?

### ISSUE THREAD

**Issue by gamesover** [spujadas/elk-docker#312]
I refered to https://stackoverflow.com/questions/46406680/syslog-driver-not-working-with-docker-compose-and-elk-stack, trying to config a similiar syslog but it seems syslog could not started.

My config is below:

Dockerfile (refer to https://elk-docker.readthedocs.io/#tweaking-the-image)
```
FROM sebp/elk

WORKDIR ${LOGSTASH_HOME}
RUN gosu logstash bin/logstash-plugin install logstash-input-syslog
```
docker-compose.yml
```
version: '3'
services:
  elk-custom:
    build: .
    restart: always
    ports:
      - 5601:5601
      - 9200:9200
      - 5044:5044
      - 55514:514 
```
Then, I simply run `docker-compose up`, the output seem good to me.
I can open 192.168.1.115:5601(the machine hosting `elk`) without any issue. 

However, I try to config one of my docker log like
```
api:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
    logging:
      driver: syslog
      options:
        tag: example-server
        labels: dev,api
        syslog-address: tcp://192.168.1.115:55514
``` 
The bash will immidiately report `ERROR: for api  Cannot start service api: failed to initialize logging driver: dial tcp 192.168.1.115:55514: connect: connection refused`

At the elk machine, I run telent to test whether 55514 port is working
```
telnet localhost 55514
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Connection closed by foreign host.
```
It seems syslog input service is not started completely, though port is binded correctly.

What am I missing? Thank you.
