### ISSUE TITLE
How to set ELASTICSEARCH_URL?

### ISSUE THREAD

**Issue by glitterlip** [spujadas/elk-docker#326]
Hi ,I am using docker machine on OSX.

When using docker toolbox/docker machine. The host ip is not 127.0.0.1, it's  192.168.99.100.

When I in elk container, I can access es using `curl 192.168.99.100:9200`. so in elk container, the kibana should connect to es use  `192.168.99.100:9200` this address.

Then I tried add an environment arg and set `ELASTICSEARCH_URL` variable in `.env` file, but when I check elk logs none of these works. It still connect to default config  and shows 
```
["warning","elasticsearch","admin"],"pid":267,"message":"Unable to revive connection: http://localhost:9200/"
```

here is my `.env` file and `docker-compose.yml`

```
elk:
  image: sebp/elk
  environment:
    - ELASTICSEARCH_URL= "http://192.168.99.100:9200"
  ports:
    - "5601:5601"
    - "9200:9200"
    - "5044:5044"
```

```
ELASTICSEARCH_URL=http://192.168.99.100:9200

```
