### ISSUE TITLE
ELK is not working !

### ISSUE THREAD

**Issue by angelcantu84** [spujadas/elk-docker#335]
Hi.
Im try to join on my container 9200, 9300, 80, 443, etc... and I don't see the website :(

# cat docker-compose
```
version: '2'
services:
  elk:
    container_name: elk
    image: sebp/elk
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    ports:
      - "80:80"
      - "443:443"
      - "5601:5601"
      - "9200:9200"
      - "9300:9300"
      - "9600:9600"
      - "5044:5044"
    environment:
      - VIRTUAL_HOST=elk.mysite.com
      - LETSENCRYPT_HOST=elk.mysite.com
      - LETSENCRYPT_EMAIL=mail@mysite.com
    volumes:
      - /home/admin/logs:/var/lib/elasticsearch:rw
      - /home/admin/backups:/var/backups:rw
    networks:
      - mired

networks:
  mired:
```

# docker-compuse up -d
```
Creating network "admin_mired" with the default driver
Creating elk ... 
Creating elk ... done
```

# docker ps
```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                                                                                                                                              NAMES
31899bd3692e        sebp/elk            "/usr/local/bin/star…"   19 seconds ago      Up 18 seconds       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:5044->5044/tcp, 0.0.0.0:5601->5601/tcp, 0.0.0.0:9200->9200/tcp, 0.0.0.0:9300->9300/tcp, 0.0.0.0:9600->9600/tcp   elk
```

But I can't access to the kibana site :(
