### ISSUE TITLE
Can't get Elk started

### ISSUE THREAD

**Issue by YouveGotMeowxy** [spujadas/elk-docker#364]
I'm using Docker Desktop in WSL2 and for the life of me I can't get it running, can anyone tell me what's wrong?

My compose:

```
services:

  elk:
    hostname: elk
    image: sebp/elk:latest
    environment:
      TZ: 'America/Chicago'
      ES_CONNECT_RETRY: '60'
      CLUSTER_NAME: 'cloud-cluster'
    volumes:
        - /opt/docker/configs/elk/kibana:/opt/kibana/config:rw     # Kibana config
        - /opt/docker/configs/elasticsearch:/etc/elasticsearch:rw   # Elasticsearch config         
        - /mnt/e/Docker/elk:/var/lib/elasticsearch:rw                      # Elasticsearch data
        - /mnt/e/Docker/Logs/elk:/var/log:rw                                 # Logs
    #ports: (I'm doing everything internally within docker's network)
        #- '9034:5601' # Kibana
        #- '9036:5044' # Logstash
        #- '9035:9200' # Elasticsearch (JSON Interface)
        #- '9300:9300' # Elasticsearch (Transport Interface: Optional)
    networks:
      - elkn
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.MainDaemon == true
      restart_policy:
        condition: any

networks:
  elkn:
    external: true
    name: monitors
```

First thing that happens straight away is this:

```
today at 11:22:38 AM * Starting periodic command scheduler cron
today at 11:22:38 AM   ...done.
today at 11:22:38 AM * Starting Elasticsearch Server
today at 11:22:40 AM**Exception in thread "main" java.nio.file.NoSuchFileException: /etc/elasticsearch/jvm.options**
today at 11:22:40 AM	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
today at 11:22:40 AM	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
today at 11:22:40 AM	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
today at 11:22:40 AM	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
today at 11:22:40 AM	at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
today at 11:22:40 AM	at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
today at 11:22:40 AM	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:422)
today at 11:22:40 AM	at java.base/java.nio.file.Files.newInputStream(Files.java:160)
today at 11:22:40 AM	at org.elasticsearch.tools.launchers.JvmOptionsParser.readJvmOptionsFiles(JvmOptionsParser.java:168)
today at 11:22:40 AM	at org.elasticsearch.tools.launchers.JvmOptionsParser.jvmOptions(JvmOptionsParser.java:124)
today at 11:22:40 AM	at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:86)
today at 11:22:40 AM   ...fail!
today at 11:22:41 AMwaiting for Elasticsearch to be up (1/60)
today at 11:22:42 AMwaiting for Elasticsearch to be up (2/60)
today at 11:22:43 AMwaiting for Elasticsearch to be up (3/60)
today at 11:22:44 AMwaiting for Elasticsearch to be up (4/60)
today at 11:22:45 AMwaiting for Elasticsearch to be up (5/60)
today at 11:22:46 AMwaiting for Elasticsearch to be up (6/60)
today at 11:22:47 AMwaiting for Elasticsearch to be up (7/60)
today at 11:22:48 AMwaiting for Elasticsearch to be up (8/60)
today at 11:22:49 AMwaiting for Elasticsearch to be up (9/60)
today at 11:22:50 AMwaiting for Elasticsearch to be up (10/60)
today at 11:22:51 AMwaiting for Elasticsearch to be up (11/60)
today at 11:22:52 AMwaiting for Elasticsearch to be up (12/60)
today at 11:22:53 AMwaiting for Elasticsearch to be up (13/60)
today at 11:22:54 AMwaiting for Elasticsearch to be up (14/60)
today at 11:22:55 AMwaiting for Elasticsearch to be up (15/60)
today at 11:22:56 AMwaiting for Elasticsearch to be up (16/60)
today at 11:22:57 AMwaiting for Elasticsearch to be up (17/60)
today at 11:22:58 AMwaiting for Elasticsearch to be up (18/60)
today at 11:22:59 AMwaiting for Elasticsearch to be up (19/60)
today at 11:23:00 AMwaiting for Elasticsearch to be up (20/60)
today at 11:23:01 AMwaiting for Elasticsearch to be up (21/60)
today at 11:23:02 AMwaiting for Elasticsearch to be up (22/60)
today at 11:23:03 AMwaiting for Elasticsearch to be up (23/60)
today at 11:23:04 AMwaiting for Elasticsearch to be up (24/60)
today at 11:23:05 AMwaiting for Elasticsearch to be up (25/60)
today at 11:23:06 AMwaiting for Elasticsearch to be up (26/60)
today at 11:23:07 AMwaiting for Elasticsearch to be up (27/60)
today at 11:23:08 AMwaiting for Elasticsearch to be up (28/60)
today at 11:23:09 AMwaiting for Elasticsearch to be up (29/60)
today at 11:23:10 AMwaiting for Elasticsearch to be up (30/60)
today at 11:23:11 AMwaiting for Elasticsearch to be up (31/60)
today at 11:23:12 AMwaiting for Elasticsearch to be up (32/60)
today at 11:23:13 AMwaiting for Elasticsearch to be up (33/60)
today at 11:23:14 AMwaiting for Elasticsearch to be up (34/60)
today at 11:23:15 AMwaiting for Elasticsearch to be up (35/60)
today at 11:23:16 AMwaiting for Elasticsearch to be up (36/60)
today at 11:23:17 AMwaiting for Elasticsearch to be up (37/60)
today at 11:23:18 AMwaiting for Elasticsearch to be up (38/60)
today at 11:23:19 AMwaiting for Elasticsearch to be up (39/60)
today at 11:23:20 AMwaiting for Elasticsearch to be up (40/60)
today at 11:23:21 AMwaiting for Elasticsearch to be up (41/60)
today at 11:23:22 AMwaiting for Elasticsearch to be up (42/60)
today at 11:23:23 AMwaiting for Elasticsearch to be up (43/60)
today at 11:23:24 AMwaiting for Elasticsearch to be up (44/60)
today at 11:23:25 AMwaiting for Elasticsearch to be up (45/60)
today at 11:23:26 AMwaiting for Elasticsearch to be up (46/60)
today at 11:23:27 AMwaiting for Elasticsearch to be up (47/60)
today at 11:23:28 AMwaiting for Elasticsearch to be up (48/60)
today at 11:23:29 AMwaiting for Elasticsearch to be up (49/60)
today at 11:23:30 AMwaiting for Elasticsearch to be up (50/60)
today at 11:23:31 AMwaiting for Elasticsearch to be up (51/60)
today at 11:23:32 AMwaiting for Elasticsearch to be up (52/60)
today at 11:23:33 AMwaiting for Elasticsearch to be up (53/60)
today at 11:23:34 AMwaiting for Elasticsearch to be up (54/60)
today at 11:23:35 AMwaiting for Elasticsearch to be up (55/60)
today at 11:23:36 AMwaiting for Elasticsearch to be up (56/60)
today at 11:23:37 AMwaiting for Elasticsearch to be up (57/60)
today at 11:23:38 AMwaiting for Elasticsearch to be up (58/60)
today at 11:23:39 AMwaiting for Elasticsearch to be up (59/60)
today at 11:23:40 AMwaiting for Elasticsearch to be up (60/60)
today at 11:23:40 AMCouldn't start Elasticsearch. Exiting.
today at 11:23:40 AMElasticsearch log follows below.
today at 11:23:41 AMContainer stopped
```

And then nothing gets written to any of the mounted volumes, or the log. No config files, nothing. I checked permissions for the config directories, and they are all root (is that correct?).

I'm not very well versed in linux and am still learning. Shouldn't the config files, including the `jvm.options` file automatically get written/copied to the mounted volumes?

When I followed your instructions and did this:

    sudo docker run -it sebp/elk:latest bash

and:

```
ES_PATH_CONF=/etc/elasticsearch gosu elasticsearch /opt/elasticsearch/bin/elasticsearch \
    -Epath.logs=/var/log/elasticsearch \
    -Epath.data=/var/lib/elasticsearch
```

it seems to run fine, so I'm thinking something is wrong with my compose? But I cant sort it out. Can anyone help me?
