### ISSUE TITLE
Issues running on AWS Fargate

### ISSUE THREAD

**Issue by diondree** [spujadas/elk-docker#373]
Hello, im currently trying to run this image on AWS Fargate using docker compose. I am stuck at the mmap boostrap check because Fargate doesnt allow you to change that but i see there's an option to disable that via the setting the environment variable  to ES_SETTING_NODE_STORE_ALLOW__MMAP=false but after doing that nothing changes so wanted to know if its just not being passed based on how this image is configured. Below is my docker-compose.yml for further reference.

```yml
version: '2'

services:
  elk:
    image: sebp/elk
    container_name: elk
    ulimits: 
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4096M

    environment:
      - ES_SETTING_NODE_STORE_ALLOW__MMAP=false
      - discovery.type=single-node
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
```
