### ISSUE TITLE
Kibana refuses connection, nothing in logs

### ISSUE THREAD

**Issue by sergesyrota** [spujadas/elk-docker#376]
I've pulled latest (`8.3.3`) image, as well as `oss-8.3.3`, and started with basic configuration using docker-compose:
```
    elk:
        image: sebp/elk:oss-8.3.3
        container_name: elk
        ports:
            - 5601:5601 # Kibana UI
            - 9200:9200 # Elastic JSON
            - 5044:5044 # Logstash Beats interface
            - 9600:9600 # Logstash monitoring API
```
Waited a few minutes... When I connect to host:5601, I get "connection refused." Same if I execute bash inside container and run curl localhost:5601.

ElasticSearch is fine, and accessible on port 9200:
```
{
"name": "elk",
"cluster_name": "elasticsearch",
"cluster_uuid": "VnfgEDfrS1SZKkQthFf27Q",
"version": {
"number": "8.3.3",
"build_flavor": "default",
"build_type": "tar",
"build_hash": "801fed82df74dbe537f89b71b098ccaff88d2c56",
"build_date": "2022-07-23T19:30:09.227964828Z",
"build_snapshot": false,
"lucene_version": "9.2.0",
"minimum_wire_compatibility_version": "7.17.0",
"minimum_index_compatibility_version": "7.0.0"
},
"tagline": "You Know, for Search"
}
```

Inside the container, `/var/log/kibana/kibana5.log` is empty. However, I see kibana process running fine:
```
root@6d660c331b7c:/# ps aux | grep kibana
kibana       199 97.4  0.0   2616   104 ?        R    18:23   1:25 start-stop-daemon --start --user kibana -c kibana --group kibana --pidfile /var/run/kibana5.pid --make-pidfile --background --exec /opt/kibana/bin/kibana -- -l /var/log/kibana/kibana5.log
```

If I kill the process, and start it in foreground manually with `gosu kibana /opt/kibana/bin/kibana`, it starts up just fine, and I'm able to access port 5601.

Any advice on what I can try for Kibana to be able to start up automatically?
